## Using GraalVM image as builder
FROM ghcr.io/graalvm/native-image:ol9-java17-22.3.3 AS builder

# Install tar and gzip to extract the Maven binaries
RUN microdnf update \
 && microdnf install --nodocs \
    tar \
    gzip \
 && microdnf clean all \
 && rm -rf /var/cache/yum

## Using Liberica NIK image as builder
#FROM bellsoft/liberica-native-image-kit-container:jdk-17-nik-22.3-glibc as builder

## Install tar and gzip to extract the Maven binaries
#RUN apk add --no-cache tar gzip curl

# Install Maven
ARG MAVEN_VERSION=3.9.4
ARG USER_HOME_DIR="/root"
ARG BASE_URL=https://dlcdn.apache.org/maven/maven-3/${MAVEN_VERSION}/binaries

RUN mkdir -p /usr/share/maven /usr/share/maven/ref \
 && curl -fsSL -o /tmp/apache-maven.tar.gz ${BASE_URL}/apache-maven-${MAVEN_VERSION}-bin.tar.gz \
 && tar -xzf /tmp/apache-maven.tar.gz -C /usr/share/maven --strip-components=1 \
 && rm -f /tmp/apache-maven.tar.gz \
 && ln -s /usr/share/maven/bin/mvn /usr/bin/mvn

ENV MAVEN_HOME /usr/share/maven
ENV MAVEN_CONFIG "$USER_HOME_DIR/.m2"

# Set the working directory to /home/app
WORKDIR /build

# Copy the source code into the image for building
COPY . /build

# Build
RUN mvn clean -Pnative -DskipTests package

FROM eclipse-temurin:17-jre-alpine
WORKDIR /opt/app
RUN addgroup --system javauser && adduser -S -s /usr/sbin/nologin -G javauser javauser
COPY --from=builder /build/target/*.jar app.jar
COPY src/main/resources/reports src/main/resources/reports
RUN chown -R javauser:javauser .
USER javauser
EXPOSE 8080
ENTRYPOINT ["java","-Dspring.aot.enabled=true" ,"-jar","app.jar"]