#FROM ghcr.io/graalvm/graalvm-community:17.0.8 AS builder
FROM ghcr.io/graalvm/graalvm-community:21.0.0-ol9 AS builder

# Install Maven
ARG MAVEN_VERSION=3.9.4
ARG USER_HOME_DIR="/root"
ARG BASE_URL=https://dlcdn.apache.org/maven/maven-3/${MAVEN_VERSION}/binaries

RUN mkdir -p /usr/share/maven /usr/share/maven/ref \
 && curl -fsSL -o /tmp/apache-maven.tar.gz ${BASE_URL}/apache-maven-${MAVEN_VERSION}-bin.tar.gz \
 && tar -xzf /tmp/apache-maven.tar.gz -C /usr/share/maven --strip-components=1 \
 && rm -f /tmp/apache-maven.tar.gz \
 && ln -s /usr/share/maven/bin/mvn /usr/bin/mvn

ENV MAVEN_HOME /usr/share/maven
ENV MAVEN_CONFIG "$USER_HOME_DIR/.m2"

# Set the working directory to /home/app
WORKDIR /build

# Copy the source code into the image for building
COPY . /build

RUN mvn install:install-file -Dfile=src/main/resources/dtLocalLib/font-tahoma.jar -DgroupId=dt.local.lib -DartifactId=dtfont-tahoma -Dversion=1.0.0 -Dpackaging=jar -DgeneratePom=true \
 && mvn install:install-file -Dfile=src/main/resources/dtLocalLib/font-dbheavent.jar -DgroupId=dt.local.lib -DartifactId=dtfont-dbheavent -Dversion=1.0.0 -Dpackaging=jar -DgeneratePom=true \
 && mvn install:install-file -Dfile=src/main/resources/dtLocalLib/font-arial-unicode.jar -DgroupId=dt.local.lib -DartifactId=dtfont-arial-unicode -Dversion=1.0.0 -Dpackaging=jar -DgeneratePom=true

# Build
RUN mvn -Pnative -DskipTests native:compile

#FROM docker.io/oraclelinux:8-slim
#FROM ubuntu:jammy
FROM debian:12.2-slim
EXPOSE 8080
COPY --from=builder build/target/dt-core app
ENTRYPOINT ["/app"]