OM_CODE=OMTESTTDM-sit
JASPER_PATH=D:\\DT_PROJECT_GITHUBBBBBBBBBBBB\\DTCoreApp-dev\\DTCore\\src\\main\\resources\\reports\\jasper\\
JASPER_PATH_IMAGE=D:\\DT_PROJECT_GITHUBBBBBBBBBBBB\\DTCoreApp-dev\\DTCore\\src\\main\\resources\\reports\\jasper\\image\\